// Generated file.  Do not edit.  Do not check in.
struct Opcode opcodes[256] = {
  { OP_BRK, MODE_IMPLIED,        7 }, // 00
  { OP_ORA, MODE_INDIRECT_X,     6 }, // 01
  { OP_XXX, MODE_IMPLIED,        0 }, // 02
  { OP_XXX, MODE_IMPLIED,        0 }, // 03
  { OP_XXX, MODE_IMPLIED,        0 }, // 04
  { OP_ORA, MODE_ZERO_PAGE,      2 }, // 05
  { OP_ASL, MODE_ZERO_PAGE,      5 }, // 06
  { OP_XXX, MODE_IMPLIED,        0 }, // 07
  { OP_PHP, MODE_IMPLIED,        3 }, // 08
  { OP_ORA, MODE_IMMEDIATE,      2 }, // 09
  { OP_ASL, MODE_ACCUMULATOR,    2 }, // 0a
  { OP_XXX, MODE_IMPLIED,        0 }, // 0b
  { OP_XXX, MODE_IMPLIED,        0 }, // 0c
  { OP_ORA, MODE_ABSOLUTE,       4 }, // 0d
  { OP_ASL, MODE_ABSOLUTE,       6 }, // 0e
  { OP_XXX, MODE_IMPLIED,        0 }, // 0f
  { OP_BPL, MODE_BRANCH,         2 }, // 10
  { OP_ORA, MODE_INDIRECT_Y,     5 }, // 11
  { OP_XXX, MODE_IMPLIED,        0 }, // 12
  { OP_XXX, MODE_IMPLIED,        0 }, // 13
  { OP_XXX, MODE_IMPLIED,        0 }, // 14
  { OP_ORA, MODE_ZERO_PAGE_X,    3 }, // 15
  { OP_ASL, MODE_ZERO_PAGE_X,    6 }, // 16
  { OP_XXX, MODE_IMPLIED,        0 }, // 17
  { OP_CLC, MODE_IMPLIED,        2 }, // 18
  { OP_ORA, MODE_ABSOLUTE_Y,     4 }, // 19
  { OP_XXX, MODE_IMPLIED,        0 }, // 1a
  { OP_XXX, MODE_IMPLIED,        0 }, // 1b
  { OP_XXX, MODE_IMPLIED,        0 }, // 1c
  { OP_ORA, MODE_ABSOLUTE_X,     4 }, // 1d
  { OP_ASL, MODE_ABSOLUTE_X,     7 }, // 1e
  { OP_XXX, MODE_IMPLIED,        0 }, // 1f
  { OP_JSR, MODE_ABSOLUTE,       6 }, // 20
  { OP_AND, MODE_INDIRECT_X,     6 }, // 21
  { OP_XXX, MODE_IMPLIED,        0 }, // 22
  { OP_XXX, MODE_IMPLIED,        0 }, // 23
  { OP_BIT, MODE_ZERO_PAGE,      3 }, // 24
  { OP_AND, MODE_ZERO_PAGE,      2 }, // 25
  { OP_ROL, MODE_ZERO_PAGE,      5 }, // 26
  { OP_XXX, MODE_IMPLIED,        0 }, // 27
  { OP_PLP, MODE_IMPLIED,        4 }, // 28
  { OP_AND, MODE_IMMEDIATE,      2 }, // 29
  { OP_ROL, MODE_ACCUMULATOR,    2 }, // 2a
  { OP_XXX, MODE_IMPLIED,        0 }, // 2b
  { OP_BIT, MODE_ABSOLUTE,       4 }, // 2c
  { OP_AND, MODE_ABSOLUTE,       4 }, // 2d
  { OP_ROL, MODE_ABSOLUTE,       6 }, // 2e
  { OP_XXX, MODE_IMPLIED,        0 }, // 2f
  { OP_BMI, MODE_BRANCH,         2 }, // 30
  { OP_AND, MODE_INDIRECT_Y,     5 }, // 31
  { OP_XXX, MODE_IMPLIED,        0 }, // 32
  { OP_XXX, MODE_IMPLIED,        0 }, // 33
  { OP_XXX, MODE_IMPLIED,        0 }, // 34
  { OP_AND, MODE_ZERO_PAGE_X,    3 }, // 35
  { OP_ROL, MODE_ZERO_PAGE_X,    6 }, // 36
  { OP_XXX, MODE_IMPLIED,        0 }, // 37
  { OP_SEC, MODE_IMPLIED,        2 }, // 38
  { OP_AND, MODE_ABSOLUTE_Y,     4 }, // 39
  { OP_XXX, MODE_IMPLIED,        0 }, // 3a
  { OP_XXX, MODE_IMPLIED,        0 }, // 3b
  { OP_XXX, MODE_IMPLIED,        0 }, // 3c
  { OP_AND, MODE_ABSOLUTE_X,     4 }, // 3d
  { OP_ROL, MODE_ABSOLUTE_X,     7 }, // 3e
  { OP_XXX, MODE_IMPLIED,        0 }, // 3f
  { OP_RTI, MODE_IMPLIED,        6 }, // 40
  { OP_EOR, MODE_INDIRECT_X,     6 }, // 41
  { OP_XXX, MODE_IMPLIED,        0 }, // 42
  { OP_XXX, MODE_IMPLIED,        0 }, // 43
  { OP_XXX, MODE_IMPLIED,        0 }, // 44
  { OP_EOR, MODE_ZERO_PAGE,      3 }, // 45
  { OP_LSR, MODE_ZERO_PAGE,      5 }, // 46
  { OP_XXX, MODE_IMPLIED,        0 }, // 47
  { OP_PHA, MODE_IMPLIED,        3 }, // 48
  { OP_EOR, MODE_IMMEDIATE,      2 }, // 49
  { OP_LSR, MODE_ACCUMULATOR,    2 }, // 4a
  { OP_XXX, MODE_IMPLIED,        0 }, // 4b
  { OP_JMP, MODE_ABSOLUTE,       3 }, // 4c
  { OP_EOR, MODE_ABSOLUTE,       4 }, // 4d
  { OP_LSR, MODE_ABSOLUTE,       6 }, // 4e
  { OP_XXX, MODE_IMPLIED,        0 }, // 4f
  { OP_BVC, MODE_BRANCH,         2 }, // 50
  { OP_EOR, MODE_INDIRECT_Y,     5 }, // 51
  { OP_XXX, MODE_IMPLIED,        0 }, // 52
  { OP_XXX, MODE_IMPLIED,        0 }, // 53
  { OP_XXX, MODE_IMPLIED,        0 }, // 54
  { OP_EOR, MODE_ZERO_PAGE_X,    4 }, // 55
  { OP_LSR, MODE_ZERO_PAGE_X,    6 }, // 56
  { OP_XXX, MODE_IMPLIED,        0 }, // 57
  { OP_CLI, MODE_IMPLIED,        2 }, // 58
  { OP_EOR, MODE_ABSOLUTE_Y,     4 }, // 59
  { OP_XXX, MODE_IMPLIED,        0 }, // 5a
  { OP_XXX, MODE_IMPLIED,        0 }, // 5b
  { OP_XXX, MODE_IMPLIED,        0 }, // 5c
  { OP_EOR, MODE_ABSOLUTE_X,     4 }, // 5d
  { OP_LSR, MODE_ABSOLUTE_X,     7 }, // 5e
  { OP_XXX, MODE_IMPLIED,        0 }, // 5f
  { OP_RTS, MODE_IMPLIED,        6 }, // 60
  { OP_ADC, MODE_INDIRECT_X,     6 }, // 61
  { OP_XXX, MODE_IMPLIED,        0 }, // 62
  { OP_XXX, MODE_IMPLIED,        0 }, // 63
  { OP_XXX, MODE_IMPLIED,        0 }, // 64
  { OP_ADC, MODE_ZERO_PAGE,      3 }, // 65
  { OP_ROR, MODE_ZERO_PAGE,      5 }, // 66
  { OP_XXX, MODE_IMPLIED,        0 }, // 67
  { OP_PLA, MODE_IMPLIED,        4 }, // 68
  { OP_ADC, MODE_IMMEDIATE,      2 }, // 69
  { OP_ROR, MODE_ACCUMULATOR,    2 }, // 6a
  { OP_XXX, MODE_IMPLIED,        0 }, // 6b
  { OP_JMP, MODE_INDIRECT,       5 }, // 6c
  { OP_ADC, MODE_ABSOLUTE,       4 }, // 6d
  { OP_ROR, MODE_ABSOLUTE,       6 }, // 6e
  { OP_XXX, MODE_IMPLIED,        0 }, // 6f
  { OP_BVS, MODE_BRANCH,         2 }, // 70
  { OP_ADC, MODE_INDIRECT_Y,     5 }, // 71
  { OP_XXX, MODE_IMPLIED,        0 }, // 72
  { OP_XXX, MODE_IMPLIED,        0 }, // 73
  { OP_XXX, MODE_IMPLIED,        0 }, // 74
  { OP_ADC, MODE_ZERO_PAGE_X,    4 }, // 75
  { OP_ROR, MODE_ZERO_PAGE_X,    6 }, // 76
  { OP_XXX, MODE_IMPLIED,        0 }, // 77
  { OP_SEI, MODE_IMPLIED,        2 }, // 78
  { OP_ADC, MODE_ABSOLUTE_Y,     4 }, // 79
  { OP_XXX, MODE_IMPLIED,        0 }, // 7a
  { OP_XXX, MODE_IMPLIED,        0 }, // 7b
  { OP_XXX, MODE_IMPLIED,        0 }, // 7c
  { OP_ADC, MODE_ABSOLUTE_X,     4 }, // 7d
  { OP_ROR, MODE_ABSOLUTE_X,     7 }, // 7e
  { OP_XXX, MODE_IMPLIED,        0 }, // 7f
  { OP_XXX, MODE_IMPLIED,        0 }, // 80
  { OP_STA, MODE_INDIRECT_X,     6 }, // 81
  { OP_XXX, MODE_IMPLIED,        0 }, // 82
  { OP_XXX, MODE_IMPLIED,        0 }, // 83
  { OP_STY, MODE_ZERO_PAGE,      3 }, // 84
  { OP_STA, MODE_ZERO_PAGE,      3 }, // 85
  { OP_STX, MODE_ZERO_PAGE,      3 }, // 86
  { OP_XXX, MODE_IMPLIED,        0 }, // 87
  { OP_DEY, MODE_IMPLIED,        2 }, // 88
  { OP_XXX, MODE_IMPLIED,        0 }, // 89
  { OP_TXA, MODE_IMPLIED,        2 }, // 8a
  { OP_XXX, MODE_IMPLIED,        0 }, // 8b
  { OP_STY, MODE_ABSOLUTE,       4 }, // 8c
  { OP_STA, MODE_ABSOLUTE,       4 }, // 8d
  { OP_STX, MODE_ABSOLUTE,       4 }, // 8e
  { OP_XXX, MODE_IMPLIED,        0 }, // 8f
  { OP_BCC, MODE_BRANCH,         2 }, // 90
  { OP_STA, MODE_INDIRECT_Y,     6 }, // 91
  { OP_XXX, MODE_IMPLIED,        0 }, // 92
  { OP_XXX, MODE_IMPLIED,        0 }, // 93
  { OP_STY, MODE_ZERO_PAGE_X,    4 }, // 94
  { OP_STA, MODE_ZERO_PAGE_X,    4 }, // 95
  { OP_STX, MODE_ZERO_PAGE_Y,    4 }, // 96
  { OP_XXX, MODE_IMPLIED,        0 }, // 97
  { OP_TYA, MODE_IMPLIED,        2 }, // 98
  { OP_STA, MODE_ABSOLUTE_Y,     5 }, // 99
  { OP_TXS, MODE_IMPLIED,        2 }, // 9a
  { OP_XXX, MODE_IMPLIED,        0 }, // 9b
  { OP_XXX, MODE_IMPLIED,        0 }, // 9c
  { OP_STA, MODE_ABSOLUTE_X,     5 }, // 9d
  { OP_XXX, MODE_IMPLIED,        0 }, // 9e
  { OP_XXX, MODE_IMPLIED,        0 }, // 9f
  { OP_LDY, MODE_IMMEDIATE,      2 }, // a0
  { OP_LDA, MODE_INDIRECT_X,     6 }, // a1
  { OP_LDX, MODE_IMMEDIATE,      2 }, // a2
  { OP_XXX, MODE_IMPLIED,        0 }, // a3
  { OP_LDY, MODE_ZERO_PAGE,      3 }, // a4
  { OP_LDA, MODE_ZERO_PAGE,      3 }, // a5
  { OP_LDX, MODE_ZERO_PAGE,      3 }, // a6
  { OP_XXX, MODE_IMPLIED,        0 }, // a7
  { OP_TAY, MODE_IMPLIED,        2 }, // a8
  { OP_LDA, MODE_IMMEDIATE,      2 }, // a9
  { OP_TAX, MODE_IMPLIED,        2 }, // aa
  { OP_XXX, MODE_IMPLIED,        0 }, // ab
  { OP_LDY, MODE_ABSOLUTE,       4 }, // ac
  { OP_LDA, MODE_ABSOLUTE,       4 }, // ad
  { OP_LDX, MODE_ABSOLUTE,       4 }, // ae
  { OP_XXX, MODE_IMPLIED,        0 }, // af
  { OP_BCS, MODE_BRANCH,         2 }, // b0
  { OP_LDA, MODE_INDIRECT_Y,     5 }, // b1
  { OP_XXX, MODE_IMPLIED,        0 }, // b2
  { OP_XXX, MODE_IMPLIED,        0 }, // b3
  { OP_LDY, MODE_ZERO_PAGE_X,    4 }, // b4
  { OP_LDA, MODE_ZERO_PAGE_X,    4 }, // b5
  { OP_LDX, MODE_ZERO_PAGE_Y,    4 }, // b6
  { OP_XXX, MODE_IMPLIED,        0 }, // b7
  { OP_CLV, MODE_IMPLIED,        2 }, // b8
  { OP_LDA, MODE_ABSOLUTE_Y,     4 }, // b9
  { OP_TSX, MODE_IMPLIED,        2 }, // ba
  { OP_XXX, MODE_IMPLIED,        0 }, // bb
  { OP_LDY, MODE_ABSOLUTE_X,     4 }, // bc
  { OP_LDA, MODE_ABSOLUTE_X,     4 }, // bd
  { OP_LDX, MODE_ABSOLUTE_Y,     4 }, // be
  { OP_XXX, MODE_IMPLIED,        0 }, // bf
  { OP_CPY, MODE_IMMEDIATE,      2 }, // c0
  { OP_CMP, MODE_INDIRECT_X,     6 }, // c1
  { OP_XXX, MODE_IMPLIED,        0 }, // c2
  { OP_XXX, MODE_IMPLIED,        0 }, // c3
  { OP_CPY, MODE_ZERO_PAGE,      3 }, // c4
  { OP_CMP, MODE_ZERO_PAGE,      3 }, // c5
  { OP_DEC, MODE_ZERO_PAGE,      5 }, // c6
  { OP_XXX, MODE_IMPLIED,        0 }, // c7
  { OP_INY, MODE_IMPLIED,        2 }, // c8
  { OP_CMP, MODE_IMMEDIATE,      2 }, // c9
  { OP_DEX, MODE_IMPLIED,        2 }, // ca
  { OP_XXX, MODE_IMPLIED,        0 }, // cb
  { OP_CPY, MODE_ABSOLUTE,       4 }, // cc
  { OP_CMP, MODE_ABSOLUTE,       4 }, // cd
  { OP_DEC, MODE_ABSOLUTE,       6 }, // ce
  { OP_XXX, MODE_IMPLIED,        0 }, // cf
  { OP_BNE, MODE_BRANCH,         2 }, // d0
  { OP_CMP, MODE_INDIRECT_Y,     5 }, // d1
  { OP_XXX, MODE_IMPLIED,        0 }, // d2
  { OP_XXX, MODE_IMPLIED,        0 }, // d3
  { OP_XXX, MODE_IMPLIED,        0 }, // d4
  { OP_CMP, MODE_ZERO_PAGE_X,    4 }, // d5
  { OP_DEC, MODE_ZERO_PAGE_X,    6 }, // d6
  { OP_XXX, MODE_IMPLIED,        0 }, // d7
  { OP_CLD, MODE_IMPLIED,        2 }, // d8
  { OP_CMP, MODE_ABSOLUTE_Y,     4 }, // d9
  { OP_XXX, MODE_IMPLIED,        0 }, // da
  { OP_XXX, MODE_IMPLIED,        0 }, // db
  { OP_XXX, MODE_IMPLIED,        0 }, // dc
  { OP_CMP, MODE_ABSOLUTE_X,     4 }, // dd
  { OP_DEC, MODE_ABSOLUTE_X,     7 }, // de
  { OP_XXX, MODE_IMPLIED,        0 }, // df
  { OP_CPX, MODE_IMMEDIATE,      2 }, // e0
  { OP_SBC, MODE_INDIRECT_X,     6 }, // e1
  { OP_XXX, MODE_IMPLIED,        0 }, // e2
  { OP_XXX, MODE_IMPLIED,        0 }, // e3
  { OP_CPX, MODE_ZERO_PAGE,      3 }, // e4
  { OP_SBC, MODE_ZERO_PAGE,      3 }, // e5
  { OP_INC, MODE_ZERO_PAGE,      5 }, // e6
  { OP_XXX, MODE_IMPLIED,        0 }, // e7
  { OP_INX, MODE_IMPLIED,        2 }, // e8
  { OP_SBC, MODE_IMMEDIATE,      2 }, // e9
  { OP_NOP, MODE_IMPLIED,        2 }, // ea
  { OP_XXX, MODE_IMPLIED,        0 }, // eb
  { OP_CPX, MODE_ABSOLUTE,       4 }, // ec
  { OP_SBC, MODE_ABSOLUTE,       4 }, // ed
  { OP_INC, MODE_ABSOLUTE,       6 }, // ee
  { OP_XXX, MODE_IMPLIED,        0 }, // ef
  { OP_BEQ, MODE_BRANCH,         2 }, // f0
  { OP_SBC, MODE_INDIRECT_Y,     5 }, // f1
  { OP_XXX, MODE_IMPLIED,        0 }, // f2
  { OP_XXX, MODE_IMPLIED,        0 }, // f3
  { OP_XXX, MODE_IMPLIED,        0 }, // f4
  { OP_SBC, MODE_ZERO_PAGE_X,    4 }, // f5
  { OP_INC, MODE_ZERO_PAGE_X,    6 }, // f6
  { OP_XXX, MODE_IMPLIED,        0 }, // f7
  { OP_SED, MODE_IMPLIED,        2 }, // f8
  { OP_SBC, MODE_ABSOLUTE_Y,     4 }, // f9
  { OP_XXX, MODE_IMPLIED,        0 }, // fa
  { OP_XXX, MODE_IMPLIED,        0 }, // fb
  { OP_XXX, MODE_IMPLIED,        0 }, // fc
  { OP_SBC, MODE_ABSOLUTE_X,     4 }, // fd
  { OP_INC, MODE_ABSOLUTE_X,     7 }, // fe
  { OP_XXX, MODE_IMPLIED,        0 }, // ff
};
